### ISSUE TITLE
not enough arguments in call to oprot.Flush

### ISSUE THREAD

**Issue by weixuqiang88** [koblas/impalathing#10]
# github.com/koblas/impalathing/services/fb303
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:114:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:138:15: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:188:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:212:15: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:262:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:286:15: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:337:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:361:15: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:411:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:435:15: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\fb303\facebookservice.go:435:15: too many errors
# github.com/koblas/impalathing/services/cli_service
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:122:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:146:16: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:199:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:223:16: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:276:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:300:16: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:353:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:377:16: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:430:20: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:454:16: cannot assign 1 values to 2 variables
..\..\src\github.com\koblas\impalathing\services\cli_service\tcliservice.go:454:16: too many errors

**Comment by koblas** [comment]
Thrift < 0.11 is required

**Comment by weixuqiang88** [comment]
oh, seems not run well, I tried 0.10.0, even 0.9.2 or 0.9.3 not well too. My go version is 1.9rc2.
