### ISSUE TITLE
splitting by tab symbol seems wrong

### ISSUE THREAD

**Issue by forward32** [koblas/impalathing#15]
Hi there!

As far as I can see you use splitting by `\t` [here](https://github.com/koblas/impalathing/blob/84e5f9c518e1d1c8f1d2de51ed27b6edb7e0355e/rowset.go#L180).

With such implementation you will always get into [this](https://github.com/koblas/impalathing/blob/84e5f9c518e1d1c8f1d2de51ed27b6edb7e0355e/rowset.go#L216) condition selecting `String` value with `\t` symbols inside.
Moreover, your application will crash with `index out of range` if you will use `MapScan()` method in situation described above.

Is it expected behavior?

**Comment by koblas** [comment]
Last time I had access to Impala, the problem was that they didn't have a standard for quoting result data that contained \t (tabs).  

That said, it shouldn't crash.  It appears to report and error and fail.

Open to suggestions.

**Comment by forward32** [comment]
>they didn't have a standard for quoting result data that contained \t (tabs).

That's sad.

So does it mean that any Impala driver works incorrectly in that situation?
Did you try [this](https://github.com/bippio/go-impala) one?

What about my situation I fixed it at SQL-level using `replace()` function, but I spent much time investigating a problem.

**Comment by koblas** [comment]
I have not tried the linked one.  When this was originally written Hive Server 2 interfacing was "new" and not supported by most implementations.  The standard was to use Beeswax as the communications layer, the go-implala project is using HiveServer2 which is the recomendation.

IMHO - probably at this point we could look at switching over, it falls under the category of I no longer have access to Impala (nor am I going to setup one just to test this).  To build/test/update the driver.

As always, welcome a patch.

**Comment by forward32** [comment]
Ok, got it.

So I close the issue since it's not easy to solve a problem with current driver implementation.
