### ISSUE TITLE
API incompatibility in files: services/fb303/fb303.go , services/status/Status.go , services/cli_service/cli_service.go 

### ISSUE THREAD

**Issue by advancedwebdeveloper** [koblas/impalathing#16]
Hi.

I was trying to build your project, by using [gollvm](https://go.googlesource.com/gollvm/) : 

> $go build -i -v -x
> WORK=/tmp/go-build171770890
> github.com/koblas/impalathing/services/fb303
> mkdir -p $WORK/b038/
> cd $WORK
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -fgo-importcfg=/dev/null -c -x c - -o /dev/null || true
> github.com/koblas/impalathing/services/cli_service
> mkdir -p $WORK/b038/_importcfgroot_/github.com/apache/thrift/lib/go
> mkdir -p $WORK/b041/
> ln -s /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a $WORK/b038/_importcfgroot_/github.com/apache/thrift/lib/go/libthrift.a
> cd /home/oceanfish81/go/src/github.com/koblas/impalathing/services/fb303
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/koblas/impalathing/services/fb303 -o $WORK/b038/_go_.o -I $WORK/b038/_importcfgroot_ ./GoUnusedProtection__.go ./fb303-consts.go ./fb303.go
> mkdir -p $WORK/b041/_importcfgroot_/github.com/apache/thrift/lib/go
> ln -s /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a $WORK/b041/_importcfgroot_/github.com/apache/thrift/lib/go/libthrift.a
> cd /home/oceanfish81/go/src/github.com/koblas/impalathing/services/cli_service
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/koblas/impalathing/services/cli_service -o $WORK/b041/_go_.o -I $WORK/b041/_importcfgroot_ ./GoUnusedProtection__.go ./cli_service-consts.go ./cli_service.go
> # github.com/koblas/impalathing/services/fb303
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:164:45: error: argument 3 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:164:54: error: argument 4 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:174:48: error: argument 3 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:174:57: error: argument 4 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:184:47: error: argument 3 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:184:56: error: argument 4 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:195:54: error: argument 3 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:195:63: error: argument 4 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:205:49: error: argument 3 has incompatible type (incompatible type for method 'Read' (different parameter types))
> ../../go/src/github.com/koblas/impalathing/services/fb303/fb303.go:205:58: error: argument 4 has incompatible type (incompatible type for method 'Read' (different parameter types))

You can read the full output [here](https://gist.github.com/advancedwebdeveloper/579985fd883b0f1eecf662c31ad8d8b1#file-impalathing_build_gollvm-log)

My version of Golang is

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
, which means that you can reproduce the bug with [this](https://drive.google.com/file/d/1n7vV2GPG09oftZj7jWceH3o23A5VOaYG/view?usp=sharing) "release" build of gollvm.

My environment:

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build566915102=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by advancedwebdeveloper** [comment]
CC @thanm @cherrymui @ianlancetaylor
CC @koblas

**Comment by koblas** [comment]
At first glance, this looks like a thrift incompatibility.

Have your rerun "make" before you did the build?

**Comment by koblas** [comment]
Since I've seen no update, closing for now.
