### ISSUE TITLE
go get throws error

### ISSUE THREAD

**Issue by ravisankarv** [koblas/impalathing#4]
I am getting this error when trying to download the code. 

Command tried: go get github.com/koblas/impalathing
Error:
github.com/koblas/impalathing/services/cli_service
src/github.com/koblas/impalathing/services/cli_service/ttypes.go:2157: cannot use byte(*p.Value) (type byte) as type int8 in argument to oprot.WriteByte

**Comment by koblas** [comment]
Given that generated code, there may be a difference in go thrift implementations.

It also appears that different protocols might implement WriteByte(byte) and WriteByte(int8) -- from reading https://github.com/apache/thrift/search?l=go&p=1&q=WriteByte&utf8=%E2%9C%93

Do you have any more details about the thrift connection your creating?

**Comment by ravisankarv** [comment]
Thanks for your quick response. 

I am currently not using thrift. Do I need thrift to run the code?

**Comment by db7** [comment]
Same issue here. Would be glad to learn about a workaround.

**Comment by koblas** [comment]
This should now be fixed in the following commit which updated to the current thrift libraries.

https://github.com/koblas/impalathing/commit/3cc75c2fe69f7066da4b4487af9a069b059d07cf
