### ISSUE TITLE
Thrift update brake code

### ISSUE THREAD

**Issue by zhujiaqi** [koblas/impalathing#5]
git.apache.org/thrift.git/lib/go/thrift now 0.10.0

Probably just need a new thrift compiler and run against .thrift files, I will try it myself and see if i can fix it.

Would you consider bringing in some version control ?

Thank you very much for your time.

build error logs:

# github.com/koblas/impalathing/services/fb303
github.com/koblas/impalathing/services/fb303/facebookservice.go:1003: cannot use facebookServiceProcessorGetName literal (type *facebookServiceProcessorGetName) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetName does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1004: cannot use facebookServiceProcessorGetVersion literal (type *facebookServiceProcessorGetVersion) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetVersion does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1005: cannot use facebookServiceProcessorGetStatus literal (type *facebookServiceProcessorGetStatus) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetStatus does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1006: cannot use facebookServiceProcessorGetStatusDetails literal (type *facebookServiceProcessorGetStatusDetails) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetStatusDetails does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1007: cannot use facebookServiceProcessorGetCounters literal (type *facebookServiceProcessorGetCounters) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetCounters does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1008: cannot use facebookServiceProcessorGetCounter literal (type *facebookServiceProcessorGetCounter) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetCounter does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1009: cannot use facebookServiceProcessorSetOption literal (type *facebookServiceProcessorSetOption) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorSetOption does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1010: cannot use facebookServiceProcessorGetOption literal (type *facebookServiceProcessorGetOption) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetOption does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1011: cannot use facebookServiceProcessorGetOptions literal (type *facebookServiceProcessorGetOptions) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetOptions does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1012: cannot use facebookServiceProcessorGetCpuProfile literal (type *facebookServiceProcessorGetCpuProfile) as type thrift.TProcessorFunction in assignment:
	*facebookServiceProcessorGetCpuProfile does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/fb303/facebookservice.go:1012: too many errors
# github.com/koblas/impalathing/services/cli_service
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1347: cannot use tCLIServiceProcessorOpenSession literal (type *tCLIServiceProcessorOpenSession) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorOpenSession does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1348: cannot use tCLIServiceProcessorCloseSession literal (type *tCLIServiceProcessorCloseSession) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorCloseSession does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1349: cannot use tCLIServiceProcessorGetInfo literal (type *tCLIServiceProcessorGetInfo) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1350: cannot use tCLIServiceProcessorExecuteStatement literal (type *tCLIServiceProcessorExecuteStatement) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorExecuteStatement does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1351: cannot use tCLIServiceProcessorGetTypeInfo literal (type *tCLIServiceProcessorGetTypeInfo) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetTypeInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1352: cannot use tCLIServiceProcessorGetCatalogs literal (type *tCLIServiceProcessorGetCatalogs) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetCatalogs does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1353: cannot use tCLIServiceProcessorGetSchemas literal (type *tCLIServiceProcessorGetSchemas) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetSchemas does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1354: cannot use tCLIServiceProcessorGetTables literal (type *tCLIServiceProcessorGetTables) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetTables does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1355: cannot use tCLIServiceProcessorGetTableTypes literal (type *tCLIServiceProcessorGetTableTypes) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetTableTypes does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1356: cannot use tCLIServiceProcessorGetColumns literal (type *tCLIServiceProcessorGetColumns) as type thrift.TProcessorFunction in assignment:
	*tCLIServiceProcessorGetColumns does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
github.com/koblas/impalathing/services/cli_service/tcliservice.go:1356: too many errors

**Comment by koblas** [comment]
Since I no longer have access to an Impala server. If you could create a pull request with an appropriate fix that would be great.
